# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HnText < Formula
  desc "a fast, easy-to-use, text-first Hacker News terminal client"
  homepage "https://github.com/piqoni/hn-text"
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/piqoni/hn-text/releases/download/v0.1.3/hn-text_Darwin_x86_64.tar.gz"
      sha256 "5100be0ee1b310ebdd1b1d4a295aa06f5ec9145a8cd9d8f0acd8b7501592bf5b"

      def install
        bin.install "hn-text"
      end
    end
    on_arm do
      url "https://github.com/piqoni/hn-text/releases/download/v0.1.3/hn-text_Darwin_arm64.tar.gz"
      sha256 "ad3918a7dafaea21051ead8f89597fc3f62898332ab8970fb22f7e8acebf1766"

      def install
        bin.install "hn-text"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/piqoni/hn-text/releases/download/v0.1.3/hn-text_Linux_x86_64.tar.gz"
        sha256 "b2f4cd3a3a786d8f8a2c8d195190d643af4e2426373fcb37d60749a76f69374f"

        def install
          bin.install "hn-text"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/piqoni/hn-text/releases/download/v0.1.3/hn-text_Linux_arm64.tar.gz"
        sha256 "f279e608810fbd6ae84b64dcf2fb67b6cdf3dafc8098eeb388484646301631b1"

        def install
          bin.install "hn-text"
        end
      end
    end
  end
end
